#!/bin/bash

export LLAMA_SERVER_URL=${LLAMA_SERVER_URL?"Please set the LLAMA_SERVER_URL environment variable."}
DOCKER_IMAGE=${DOCKER_IMAGE:-opencode:latest}
exec docker run --rm -it \
    -e TERM \
    -e ALL_PROXX \
    -e HTTP_PROXY \
    -e HTTPS_PROX \
    -e UID=${EUID} \
    -e LLAMA_SERVER_URL \
    -e LLAMA_MODEL \
    --name opencode-${LOGNAME} \
    -v opencode-${LOGNAME}:/workspace \
    -v "${PWD}":/workspace/workdir \
        "$DOCKER_IMAGE" \
            $*
