#!/bin/bash
TARGET_DB=/workspace/.local/share/opencode/opencode.db

if [ -f "$TARGET_DB" ]; then
    sqlite3 "$TARGET_DB" <<EOF
        DELETE FROM message WHERE session_id IN (SELECT id FROM sessions WHERE archived = 1);
        DELETE FROM session WHERE archived = 1;
        VACUUM;
EOF
fi
